name: 部署VitePress文档至GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装依赖
        run: npm install

      - name: 打包静态文档
        run: npm run build

      - name: 上传打包产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vitepress/dist

  deploy-page:
    needs: build-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 发布站点
        id: deploy
        uses: actions/deploy-pages@v4
